# Generated by Django 2.2.1 on 2019-06-08 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoList', '0003_todolist'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
