# Generated by Django 2.2.1 on 2019-06-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoList', '0004_todolist_is_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='due_by',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
