# Generated by Django 2.2.1 on 2019-06-09 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TodoList', '0005_auto_20190609_0225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'ordering': ['-created_at']},
        ),
    ]
